name: Get Selected Environments
id: get-envs-action
description: Get Selected Environments
icon: "check"
color: "black"
on:
  workflow-call:
inputs:
  data:
    description: inputs for check input
    required: true
runs:
  using: "composite"
  steps:
    - name: Parse input
      id: parse-input
      shell: bash
      run: |
        inputs=($INPUTS)
                
        
                
        echo "${{fromJSON(inputs.data)}}" >> "$GITHUB_OUTPUT"
      env:
        INPUTS: ${{ inputs.data }}