name: Get Selected Environments
id: get-envs-action
description: Get Selected Environments
icon: "check"
color: "black"
on:
  workflow-call:
inputs:
  data:
    description: inputs for check input
    required: true
runs:
  using: "composite"
  steps:
    - name: Parse input
      id: parse-input
      shell: bash
      run: |                
        declare -A inputsMap
        declare -i count=0
        for i in ${env.INPUTS[@]}; do
          if ! [[ ${env.INPUTS[i]} ]] ; then
            inputsMap["$count"]=env.INPUTS["$i"]
            count=$((count+1))
          fi
        done
                
        echo "${{join(env.inputsMap, ',')}}" >> "$GITHUB_OUTPUT"
      env:
        INPUTS: ${{ inputs.data }}