name: Get Selected Environments
id: get-envs-action
description: Get Selected Environments
icon: "check"
color: "black"
on:
  workflow-call:
inputs:
  inputs:
    description: inputs for check input
    required: true
runs:
  using: "composite"
  steps:
    - name: Parse input
      id: parse-input
      shell: bash
      run: |
        inputs=($INPUTS)
        
        declare -A inputsMap
        for i in ${inputs[@]}; do
          if ! [[ ${i} ]] ; then
            inputsMap["$i"]=1
          fi
        done
        
        echo "${{join(${inputsMap}, ',')}}" >> "$GITHUB_OUTPUT"
      env:
        INPUTS: ${{ inputs.inputs }}