name: Get Selected Environments
id: get-envs-action
description: Get Selected Environments
icon: "check"
color: "black"
on:
  workflow-call:
inputs:
  data:
    description: inputs for check input
    required: true
runs:
  using: "composite"
  steps:
    - name: Process Inputs
      id: process-inputs
      outputs:
        processed-data: ${{ fromJSON(inputs.data) }}
    - name: Parse input
      id: parse-input
      needs: [process-inputs]
      shell: bash
      run: |
        inputs=($INPUTS)
        
        declare -A inputsMap
        declare -i count=0
        for i in ${inputs[@]}; do
          if ! [[ ${inputs[i]} ]] ; then
            inputsMap["$count"]=inputs[i]
            count=$((count+1))
          fi
        done
                
        echo "${{join(env.inputsMap, ',')}}" >> "$GITHUB_OUTPUT"
      env:
        INPUTS: ${{ needs.process-inputs.outputs.processed-data }}