on:
  workflow_dispatch:
    inputs:
      env1:
        description: env1
        type: boolean
        required: false
      env2:
        description: env2
        type: boolean
        required: false
      env3:
        description: env3
        type: boolean
        required: false

jobs:
  setup-environments:
    runs-on: ubuntu-latest
    steps:
      - name: Set Environments
        id: set-environments
        shell: bash
        run: |
          function join { local IFS="$1"; shift; echo "$*"; }
          declare -A envArray=$(echo $INPUTS | jq 'to_entries | map(select(.value == true))[] | (.key)')
          result=$(join , ${envArray[@]})
          echo $result
        env:
          INPUTS: ${{ toJSON(inputs) }}
