on:
  workflow_dispatch:
    inputs:
      env1:
        description: env1
        type: boolean
        required: false
      env2:
        description: env2
        type: boolean
        required: false
      env3:
        description: env3
        type: boolean
        required: false

jobs:
  setup-environments:
    runs-on: ubuntu-latest
    steps:
      - name: Set Environments
        id: set-environments
        shell: bash
        run: |
          inputs=($INPUTS)

          declare -A inputsMap
          declare -i count=0
          for i in ${inputs[@]}; do
            if ! [[ ${inputs[i]} ]] ; then
              echo "$i"
              inputsMap["$count"]=inputs["$i"]
              count=$((count+1))
            fi
          done

          echo "${{join(env.inputsMap, ',')}}" >> "$GITHUB_OUTPUT"
        env:
          INPUTS: ${{ inputs }}
