on:
  workflow_dispatch:
    inputs:
      env1:
        description: env1
        type: boolean
        required: false
      env2:
        description: env2
        type: boolean
        required: false
      env3:
        description: env3
        type: boolean
        required: false

jobs:
  setup-environments:
    runs-on: ubuntu-latest
    steps:
      - name: Set Environments
        id: set-environments
        shell: bash
        run: |
          echo "All keys:" $(echo $INPUTS | jq 'keys')
          echo $(echo $INPUTS | jq 'to_entries | map(select(.value == true))[] | (.key)') >> $GITHUB_OUTPUT
        env:
          INPUTS: ${{ toJSON(inputs) }}
