on:
  workflow_dispatch:
    inputs:
      env1:
        description: env1
        type: boolean
        required: false
      env2:
        description: env2
        type: boolean
        required: false
      env3:
        description: env3
        type: boolean
        required: false

jobs:
  setup-environments:
    runs-on: ubuntu-latest
    outputs:
      envs: ${{ steps.set-environments.outputs.set-environments }}
    steps:
      - name: Set Environments
        id: set-environments
        shell: bash
        run: |
          function join { local IFS="$1"; shift; echo "$*" | tr -d '"'; }
          declare -A envArray=$(echo $INPUTS | jq 'to_entries | map(select(.value == true))[] | (.key|tr -d '"')')
          declare -A envJson=$(jq --compact-output --null-input '$ARGS.positional' --args -- "${envArray[@]}") 
          echo "set-environments=${envJson}" >> $GITHUB_OUTPUT
        env:
          INPUTS: ${{ toJSON(inputs) }}
  example_matrix:
    runs-on: ubuntu-latest
    needs: [setup-environments]
    strategy:
      matrix:
        version: ${{ fromJSON(needs.setup-environments.outputs.envs) }}
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.version }}
